### ISSUE TITLE
Local attention for 1d sequences

### ISSUE THREAD

**Issue by EelcoHoogendoorn** [zzd1992/Image-Local-Attention#1]
Thanks for this implementation; more or less exactly what I was looking for. Except that I was looking for an efficient implementation of local attention for a 1d-sequence.

Do you think there would be any significant compromise in simply treating my 1d sequence as a (n,1) image? My guess would be no, but as the author you probably have a better intuition of that.

Checking the code it seems like it should achieve the intended result (an attention matrix that has a finite band-limit), and I cant think of a significant performance compromise myself.

**Comment by EelcoHoogendoorn** [comment]
Another related concern; these [n, 1] filter windows might be [512, 1] in practice; a few orders of magnitude outside of the range this was perhaps designed for. Would that lead to any issues, or should it be fine?

**Comment by zzd1992** [comment]
@EelcoHoogendoorn
My implementation is designed for small 2D attention windows (reducing memory cost).
This implementation also works for 1d sequence and 1D windows because they are special cases of 2D images and 2D windows.

However, the performance of CUDA code is sensitive to data configurations. I guess there are better implementations (faster speed) for very large windows.

**Comment by EelcoHoogendoorn** [comment]
Somewhat to my surprise I havnt found any optimized finite bandwidth 1d attention implementations yet. But ill keep looking, thanks for the feedback!
